[DEFAULT]
debug = false
smtp_server = localhost
error_email_from = ckan@localhost

[app:main]
use = config:../ckan/test-core.ini

# Insert any custom config settings to be used when running your extension's
# tests here. These will override the one defined in CKAN core's test-core.ini
ckan.plugins = file_keeper_cloud


ckan.files.storage.azure.type = ckan:azure_blob
ckan.files.storage.azure.initialize = true
ckan.files.storage.azure.account_url = %(CKAN_FILE_KEEPER_TEST_AZURITE_ACCOUNT_URL)s
ckan.files.storage.azure.account_name = %(CKAN_FILE_KEEPER_TEST_AZURITE_ACCOUNT_NAME)s
ckan.files.storage.azure.account_key = %(CKAN_FILE_KEEPER_TEST_AZURITE_ACCOUNT_KEY)s
ckan.files.storage.azure.container_name = %(CKAN_FILE_KEEPER_TEST_AZURITE_CONTAINER_NAME)s

ckan.files.storage.s3.type = ckan:s3
ckan.files.storage.s3.initialize = true
ckan.files.storage.s3.endpoint = %(CKAN_FILE_KEEPER_TEST_MINIO_ENDPOINT)s
ckan.files.storage.s3.key = %(CKAN_FILE_KEEPER_TEST_MINIO_KEY)s
ckan.files.storage.s3.secret = %(CKAN_FILE_KEEPER_TEST_MINIO_SECRET)s
ckan.files.storage.s3.bucket = %(CKAN_FILE_KEEPER_TEST_MINIO_BUCKET)s

ckan.files.storage.gcs.type = ckan:gcs
ckan.files.storage.gcs.initialize = true
ckan.files.storage.gcs.project_id = test
ckan.files.storage.gcs.bucket_name = ckanext-file-keeper-cloud
ckan.files.storage.gcs.client_options = {"api_endpoint": "%(CKAN_FILE_KEEPER_TEST_GCS_ENDPOINT)s"}


# Logging configuration
[loggers]
keys = root, ckan, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_ckan]
qualname = ckan
handlers =
level = INFO

[logger_sqlalchemy]
handlers =
qualname = sqlalchemy.engine
level = WARN

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
