from __future__ import annotations

import pytest
from faker import Faker

import ckan.plugins.toolkit as tk
from ckan import types
from ckan.lib import files
from ckan.tests.helpers import call_action  # pyright: ignore[reportUnknownVariableType]

from ckanext.file_keeper_cloud import adapters


@pytest.fixture
def storage(request: pytest.FixtureRequest, with_plugins: None):
    """Fixture to provide a storage instance based on the parametrized storage name.

    The storage name is expected to be provided via the `param` attribute of
    the request object, which is set by the `pytest.mark.parametrize` decorator
    in the test class. The fixture retrieves the storage instance using
    `files.get_storage` and ensures that any existing files in the storage are
    removed before the tests run to avoid clashes with generated file names.
    """
    name = getattr(request, "param", None)
    if not name:
        pytest.fail("Storage name is not specified via parametrized mark")

    obj = files.get_storage(name)
    # remove existing files, aka. `clean_storage` to avoid clashes of names
    # generated by faker.
    for name in obj.scan():
        obj.remove(files.FileData.from_string(name))

    return obj


@pytest.mark.parametrize("storage", ["s3", "azure", "gcs"], indirect=True)
class TestShared:
    """Test shared behavior of cloud adapters."""

    def test_storage_type(self, storage: files.Storage):
        """Test that the storage instance is of the expected type based on the storage name."""
        types: dict[str, type[files.Storage]] = {
            "s3": adapters.S3Storage,
            "azure": adapters.AzureBlobStorage,
            "gcs": adapters.GoogleCloudStorage,
        }
        expected = types[storage.settings.name]
        assert type(storage) is expected

    def test_low_level_operations(self, storage: files.Storage, faker: Faker):
        """Test low-level operations of the storage: upload, check existence, retrieve content, and remove."""
        name = files.Location(faker.file_name())
        content = faker.binary(10)

        upload = files.make_upload(content)

        info = storage.upload(name, upload)

        assert info.size == len(content)
        assert info.location == name

        assert storage.exists(info)

        assert storage.content(info) == content

        storage.remove(info)
        assert not storage.exists(info)

    @pytest.mark.usefixtures("clean_db")
    def test_factory_creation(self, storage: files.Storage, file_factory: types.TestFactory, faker: Faker):
        """Test that a file can be created using the factory and retrieved from the storage with the correct content."""
        name = faker.file_name()
        content = faker.binary(10)

        file = file_factory(storage=storage.settings.name, name=name, upload=content)
        info = files.FileData.from_dict(file)
        assert storage.content(info) == content

    @pytest.mark.usefixtures("clean_db")
    def test_api_register(self, storage: files.Storage, faker: Faker):
        """Test that a file can be registered via the API and that duplicate registration raises a validation error."""
        name = files.Location(faker.file_name())
        content = faker.binary(10)
        info = storage.upload(name, files.make_upload(content))

        file = call_action("file_register", location=name, storage=storage.settings.name)
        assert info.size == file["size"]
        assert info.hash == file["hash"]

        with pytest.raises(tk.ValidationError):
            call_action("file_register", location=name, storage=storage.settings.name)

    @pytest.mark.usefixtures("clean_db")
    def test_api_delete(self, storage: files.Storage, file_factory: types.TestFactory):
        """Test that a file can be deleted via the API and that it is removed from the storage."""
        file = file_factory(storage=storage.settings.name)
        info = files.FileData.from_dict(file)
        assert storage.exists(info)

        call_action("file_delete", id=file["id"])
        assert not storage.exists(info)
